########################################
########################################
##
##  \file   .travis.yml
##  \brief  Travis-CI configuration file
##  \author J. Caleb Wherry
##
########################################
########################################

language: 
  - cpp

compiler:
  - gcc
#  - clang

before_install:

  # Repo updates for g++4.8:
  - if [ "${CXX}" = "g++" ]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    fi

  # Repo updates for clang++-3.4:
  - if [ "${CXX}" = "clang++" ]; then
      sudo add-apt-repository -y ppa:h-rayflood/llvm;
    fi

  # Update repo:
  - sudo apt-get update;

install:
 
  # Install newest GNU gcc compiler:
  - if [ "${CXX}" = "g++" ]; then
      sudo apt-get install g++-4.8;
      export CXX="g++-4.8" CC="gcc-4.8";
    fi

  # Main apt-get installs:
  - sudo apt-get install python3 python-pip

  # Install python modules:
  - sudo pip install colorama

before_script:

  # Put installed colorama package in correct place for new python version. This is extremely sloppy and nasty but 
  #  it is the quickest way I could it to work on Travis:
  - sudo mkdir /usr/local/lib/python3.2/dist-packages/colorama/
  - sudo cp /usr/local/lib/python2.7/dist-packages/colorama/* /usr/local/lib/python3.2/dist-packages/colorama/

script:
  - "./build.py"
  - "./build-debug/build-files/prime-factors ../../prime-factors/test-data.txt"

notifications:
  recipients:
    - calebwherry@gmail.com
  email:
    on_success: always
    on_failure: always
