########################################
########################################
##
##  \file   .travis.yml
##  \brief  Travis-CI configuration file
##  \author J. Caleb Wherry
##
########################################
########################################

language: 
  - cpp

compiler:
  - gcc
#  - clang

before_install:

  # Repo updates for g++4.8:
  - if [ "${CXX}" = "g++" ]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    fi

  # Repo updates for clang++-3.4:
  - if [ "${CXX}" = "clang++" ]; then
      sudo add-apt-repository -y ppa:h-rayflood/llvm;
    fi

  # Update repo:
  - sudo apt-get update;

install:
 
  # Install newest GNU gcc compiler:
  - if [ "${CXX}" = "g++" ]; then
      sudo apt-get install g++-4.8;
      export CXX="g++-4.8" CC="gcc-4.8";
    fi

  # Main apt-get installs:
  - sudo apt-get install python3 python3-pip

  # Install python modules:
  - sudo pip3 install colorama

script:
  - "./build.py"

notifications:
  recipients:
    - calebwherry@gmail.com
  email:
    on_success: always
    on_failure: always
